version: '3'

volumes:
  mysql_data: { }

services:

  db:
    image: mysql:8
    ports:
      - "3366:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=insecure_password
      - MYSQL_DATABASE=test
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8MB4;' --sql-mode="NO_ENGINE_SUBSTITUTION" --innodb-flush-log-at-trx-commit=0

